### PR TITLE
upgrade AnalysisBase. Previous version was  1yo.

### PR DESCRIPTION
**Pull request by ivukotic**

### CODE REVIEW

**Comment by BenGalewsky** [comment]
This is really up for @gordonwatts to review. Please do not merge this without his approval!

**Comment by ivukotic** [comment]
I have just tested it and it works on all the samples I tried. What's the timescale to get this in? btw: I see a bit higher CPU utilization with this version. It also solves some issues with xcache usage (not that we use it).

**Comment by gordonwatts** [comment]
Crap - I've got my notifications setup wrong in github - I totally missed this has occured, sorry! Will try to check this weekend.

**Comment by gordonwatts** [comment]
This looks good to me! I'm going to merge it.

**Review by gordonwatts — APPROVED** [review]
Looks fine, and tests ok too.

**Pull request merged**
